module.exports = (term, CRN) => {
    var CRN_val = ["", "", "", "", "", "", "", "", "", ""];
    for (var i = 0; i < CRN.length; i++){
        CRN_val[i] = CRN[i];
    }
    var obj = {
        "term_in": 		    term,
        "RSTS_IN": 		    "RW",
        "assoc_term_in": 	"DUMMY",
        "CRN_IN": 		    CRN_val[0],
        "start_date_in":    "DUMMY",
        "end_date_in":      "DUMMY",
        "SUBJ": 			"DUMMY",
        "CRSE":			    "DUMMY",
        "SEC":			    "DUMMY",
        "LEVL":			    "DUMMY",
        "CRED":			    "DUMMY",
        "GMOD":			    "DUMMY",
        "TITLE":			"DUMMY",
        "MESG":			    "DUMMY",
        "REG_BTN": 		    "Submit Changes",
        "RSTS_IN": 		    "RW",
        "CRN_IN": 		    CRN_val[1],
        "assoc_term_in":	"",
        "start_date_in":	"",
        "end_date_in":	    "",
        "RSTS_IN": 		    "RW",
        "CRN_IN": 		    CRN_val[2],
        "assoc_term_in":	"",
        "start_date_in":	"",
        "end_date_in":	    "",
        "RSTS_IN": 		    "RW",
        "CRN_IN": 		    CRN_val[3],
        "assoc_term_in":	"",
        "start_date_in":	"",
        "end_date_in":	    "",
        "RSTS_IN": 		    "RW",
        "CRN_IN": 	        CRN_val[4],
        "assoc_term_in":	"",
        "start_date_in":	"",
        "end_date_in":	    "",
        "RSTS_IN": 		    "RW",
        "CRN_IN": 		    CRN_val[5],
        "assoc_term_in":	"",
        "start_date_in":	"",
        "end_date_in":	    "",
        "RSTS_IN": 		    "RW",
        "CRN_IN": 		    CRN_val[6],
        "assoc_term_in":	"",
        "start_date_in":	"",
        "end_date_in":	    "",
        "RSTS_IN": 		    "RW",
        "CRN_IN": 		    CRN_val[7],
        "assoc_term_in":	"",
        "start_date_in":	"",
        "end_date_in":	    "",
        "RSTS_IN": 		    "RW",
        "CRN_IN": 		    CRN_val[8],
        "assoc_term_in":	"",
        "start_date_in":	"",
        "end_date_in":	    "",
        "RSTS_IN": 		    "RW",
        "CRN_IN": 		    CRN_val[9],
        "assoc_term_in":	"",
        "start_date_in":	"",
        "end_date_in":	    "",

        "assoc_term_in":    "",
        "start_date_in":	"",
        "end_date_in":	    "",
        "regs_row": 		"0",
        "wait_row": 		"0",
        "add_row": 		    "10"
    }

    return obj;
}
